apiVersion: v1
kind: Service
metadata:
  name: my-redis-service
  namespace: wallet-namespace
spec:
  selector:
    app: my-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
