apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-redis
  namespace: wallet-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-redis
  template:
    metadata:
      labels:
        app: my-redis
    spec:
      containers:
      - name: my-redis
        image: redis:alpine
        ports:
        - containerPort: 6379