apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-api
  template:
    metadata:
      labels:
        app: my-api
    spec:
      containers:
      - name: my-api
        image: engrmarkk/fastapi_kubernetes_api:1.0
        ports:
        - containerPort: 8000
        env:
        
        