"""empty message

Revision ID: 1cf651675954
Revises: 93a2f9558c0a
Create Date: 2025-01-27 23:57:40.877085

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1cf651675954"
down_revision = "93a2f9558c0a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
