"""levels table

Revision ID: 49fa1b695498
Revises: 5992e213f4c7
Create Date: 2025-02-15 07:11:02.032875

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "49fa1b695498"
down_revision = "5992e213f4c7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_levels",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("level", sa.String(length=255), nullable=True),
        sa.Column("max_balance", sa.Float(), nullable=True),
        sa.Column("max_tf_per_day", sa.Float(), nullable=True),
        sa.Column("max_tf_once", sa.Float(), nullable=True),
        sa.Column("unlimited", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("transactions", sa.Column("book_balance", sa.Float(), nullable=True))
    op.add_column("user_account", sa.Column("book_balance", sa.Float(), nullable=True))
    op.add_column(
        "users", sa.Column("account_level_id", sa.String(length=50), nullable=True)
    )
    op.create_foreign_key(None, "users", "account_levels", ["account_level_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "account_level_id")
    op.drop_column("user_account", "book_balance")
    op.drop_column("transactions", "book_balance")
    op.drop_table("account_levels")
    # ### end Alembic commands ###
