"""empty message

Revision ID: 5992e213f4c7
Revises: 5a3ddcaa3e63
Create Date: 2025-01-30 10:31:30.240840

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5992e213f4c7"
down_revision = "5a3ddcaa3e63"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
