"""empty message

Revision ID: 5a3ddcaa3e63
Revises: cf40d9a1742c
Create Date: 2025-01-30 10:28:07.176488

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5a3ddcaa3e63"
down_revision = "cf40d9a1742c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_sessions", sa.Column("used_otp", sa.Boolean(), nullable=True))
    op.add_column("user_sessions", sa.Column("used_token", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_sessions", "used_token")
    op.drop_column("user_sessions", "used_otp")
    # ### end Alembic commands ###
