"""empty message

Revision ID: 93a2f9558c0a
Revises: 363e83e5b0ca
Create Date: 2025-01-27 23:56:57.772995

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "93a2f9558c0a"
down_revision = "363e83e5b0ca"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
