"""empty message

Revision ID: cf40d9a1742c
Revises: 1cf651675954
Create Date: 2025-01-28 15:55:54.876474

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cf40d9a1742c"
down_revision = "1cf651675954"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
