apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-celery
  namespace: wallet-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-celery
  template:
    metadata:
      labels:
        app: my-celery
    spec:
      containers:
      - name: my-celery
        image: engrmarkk/fastapi_kubernetes_celery:1.0
        envFrom:
        - configMapRef:
            name: my-configmap
        - secretRef:
            name: my-secret